In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 23 02:11:18 2022

@author: darshanRaghunath
"""

# -*- coding: utf-8 

import pandas as pd
df1 = pd.read_csv("C:/Users/darshanRaghunath/bookKalyan1.csv")
col=["8","9"]
df1 = df1[col]




df2 = pd.read_csv("C:/Users/darshanRaghunath/book19.csv")
df2 = df2[col]


 



vocab_size = 5000
embedding_dim = 64
max_length = 50
trunc_type = 'post'
padding_type = 'post'
oov_tok = '<OOV>'
training_portion = .7
num_epochs = 8







#print(df.head())

df1.columns = ['Paragraph', 'class']
df2.columns = ['Paragraph', 'class']
#print(df.head())
#print(df.info())




from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import precision_recall_fscore_support
import csv
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences



#stratify=df['class']



articles = []
labels = []
count=1



noise =0
for i  in df2["Paragraph"]:
        noise += 1
        articles.append(i)    
        if(noise> 3400):
            break
        
        
noise =0    
for i  in df1["Paragraph"]:
        noise += 1
        articles.append(i)    
        if(noise>6900):
            break
        
    
    
    
noise =0        
        
print(len(articles))     
for i in df2["class"]:
    l=[]
    noise += 1
    l.append(i)
    labels.append(l)
    if(noise> 3400):
        break
    
noise =0   
    
for i in df1["class"]:
    l=[]
    noise += 1
    l.append(i)
    labels.append(l)
    if(noise> 6900):
        break
    
    
print(len(labels))



#print(labels[100])
#print(articles[100])

train_articles,validation_articles , train_labels,validation_labels  = train_test_split(articles,labels,test_size=(1-training_portion),random_state = 100)


evalSize = int(len(validation_articles) * 0.3)


evaluate_articles = validation_articles [0:evalSize]
evaluate_labels = validation_labels[0:evalSize]
                                    
validation_articles= validation_articles[evalSize :]
validation_labels =  validation_labels[evalSize :]



print("Validation")
print(len(validation_articles))


print("Evaluation")
print(len(evaluate_articles))

'''

train_size = int(len(articles) * training_portion)
train_articles = articles[0: train_size]
train_labels = labels[0: train_size]

validation_articles = articles[train_size:]
validation_labels = labels[train_size:]

#print(len(validation_labels[0]))

'''



#print(train_size)
print("train and validation")

print(len(train_articles))
print(len(train_labels))
print(len(validation_articles))
print(len(validation_labels))




tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok,filters='+-',)
tokenizer.fit_on_texts(train_articles)
word_index = tokenizer.word_index
#print(word_index)
#dict(list(word_index.items())[0:10])


train_sequences = tokenizer.texts_to_sequences(train_articles)
#print(train_sequences[100])




train_padded = pad_sequences(train_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print(len(train_sequences[0]))
print(len(train_padded[0]))

print(len(train_sequences[1]))
print(len(train_padded[1]))

print(len(train_sequences[10]))
print(len(train_padded[10]))









validation_sequences = tokenizer.texts_to_sequences(validation_articles)
validation_padded = pad_sequences(validation_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)



evaluate_sequences = tokenizer.texts_to_sequences(evaluate_articles)
evaluate_padded = pad_sequences(evaluate_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

print(len(validation_sequences))
print(validation_padded.shape)



reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_article(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])
print(decode_article(train_padded[100]))
print('---')
print(train_articles[100])

print()
print()


print(decode_article(train_padded[5005]))
print('---')
print(train_articles[5005])



train_labels =np.array(train_labels)
validation_labels = np.array(validation_labels)



evaluate_labels= np.array(evaluate_labels)




'''
#X_train, X_test, y_train, y_test = train_test_split(df['Paragraph'], df['class'],test_size=0.1)
#print(X_train[10:20])
#print(y_train[10:20])


train = df[0:3000]
test = df[3000:]
print(train.head())
print(train.info())

print(test.head())
print(test.info())


#print(train[0])

#print(len(X_train)) 
#print(type(X_train[2]))
import csv
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

'''

: 

In [ ]:
model = tf.keras.Sequential([
    # Add an Embedding layer expecting input vocab of size 5000, and output embedding dimension of size 64 we set at the top
    tf.keras.layers.Embedding(vocab_size, embedding_dim),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim)),
    #tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)),
    # use ReLU in place of tanh function since they are very good alternatives of each other.
    tf.keras.layers.Dense(embedding_dim, activation='relu'),
    # Add a Dense layer with 6 units and softmax activation.
    # When we have multiple outputs, softmax convert outputs layers into a probability distribution.
    tf.keras.layers.Dense(7, activation='softmax')
])
model.summary()

#print(train_labels.size)
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


history = model.fit(train_padded, train_labels, epochs=num_epochs, validation_data=(validation_padded, validation_labels), verbose=2)

model.save("E:/model/pvp")

'''
y_prd =model.predict(validation_padded)
print(len(validation_padded))
print(len(y_prd))
print(validation_labels[0])
#y_prd1 =np.argmax(y_prd)
print(np.argmax(y_prd[0]))
#print(confusion_matrix(validation_labels, y_prd1))
'''


y_prd =model.predict(evaluate_padded)
#print(len(validation_padded))
#print(len(y_prd))
#print(validation_labels[0])
#y_prd1 =np.argmax(y_prd)
#print(np.argmax(y_prd[0]))
#print(confusion_matrix(validation_labels, y_prd1))





ycorrect = []
ypred = []

for i in range(len(evaluate_padded)):
    ycorrect.append(evaluate_labels[i][0])
    ypred.append(np.argmax(y_prd[i]))
    
    
print(confusion_matrix(ycorrect, ypred ))



Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 64)          320000    
                                                                 
 bidirectional_4 (Bidirectio  (None, 128)              66048     
 nal)                                                            
                                                                 
 dense_8 (Dense)             (None, 64)                8256      
                                                                 
 dense_9 (Dense)             (None, 7)                 455       
                                                                 
Total params: 394,759
Trainable params: 394,759
Non-trainable params: 0
_________________________________________________________________
Epoch 1/8
226/226 - 25s - loss: 0.7052 - accuracy: 0.7749 - val_loss: 0.2244 - val_accuracy: 0.9418 - 25s/epoch - 

INFO:tensorflow:Assets written to: E:/model/pvp\assets


INFO:tensorflow:Assets written to: E:/model/pvp\assets


[[ 65   0   0   4   1   0]
 [  0  28   0   0   1   0]
 [  0   1  58   1   1   0]
 [ 11   1   1 383   1   0]
 [  0   1   1   4 326   0]
 [  0   0   0   0   0  38]]


In [ ]:
mat = confusion_matrix(ycorrect, ypred )

percent=[]
for i in range(len(mat)):
    denum=0
    num=0
    for j in range(len(mat[i])):
        if(i ==j):
            num = mat[i][i]
        
        denum += mat[i][j]
    percent.append(num/denum)
        
print(percent)

[0.9285714285714286, 0.9655172413793104, 0.9508196721311475, 0.964735516372796, 0.9819277108433735, 1.0]


In [ ]:
output =["Title", "Author", "Affiliation" , "Abstract", "Noise", "Image" ,"ID's"]

for i in range(len(percent)):
    print(output[i], percent[i])
    
    

Title 0.9285714285714286
Author 0.9655172413793104
Affiliation 0.9508196721311475
Abstract 0.964735516372796
Noise 0.9819277108433735
Image 1.0
